application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "diner"
discord_oauth:
  uri: "https://discord.com"
  auth_url: "/oauth2/authorize"
  token_url: "/api/oauth2/token"
  revoke_url: "/api/oauth2/token/revoke"
discord_api:
  uri: "https://discordapp.com"
  user_path: "/api/users/@me"