application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "diner"
discord_oauth:
  auth_url: "https://discord.com/oauth2/authorize"
  token_url: "https://discord.com/api/oauth2/token"
  revoke_url: "https://discord.com/api/oauth2/token/revoke"
discord_api:
  url: "https://discordapp.com/api"